dist: ubuntu
language: python
rvm: 2.3.4

branches:
  only:
  - master

sudo: required

services:
  - docker

#before_script:
#  - gem install berkshelf

script:
  - git clone https://github.com/perfectsense/travis-docker-deploy.git && travis-docker-deploy/docker-deploy.sh
